# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  greatminds-nexus-registry:
    type: npm-registry
    url: https://nexus.greatminds.dev/repository/npm/
    username: ${{secrets.NEXUS_REGISTRY_USERNAME}}
    password: ${{secrets.NEXUS_REGISTRY_PASSWORD}}
updates:
  - package-ecosystem: npm
    directory: '/'
    registries:
      - greatminds-nexus-registry
    schedule:
      interval: daily
      time: '02:00'
    open-pull-requests-limit: 30
    target-branch: develop
